IF OBJECT_ID('dbo.categories', 'U') IS NULL
create table dbo.categories
(
    category_id   bigint identity
        primary key,
    category_name varchar(100) not null
        constraint UK41g4n0emuvcm3qyf1f6cn43c0
            unique
)
go

IF OBJECT_ID('dbo.ingredients', 'U') IS NULL
create table dbo.ingredients
(
    ingredient_id   bigint identity
        primary key,
    entry_date      date,
    ingredient_name varchar(100) not null
        constraint UKpyr0e9eueat1dtgp9ieo6oudb
            unique,
    price_from      real
        check ([price_from] >= 1001),
    price_to        real
        check ([price_to] >= 1001),
    producer_name   varchar(100),
    supplier        varchar(100),
    category_id     bigint       not null
        constraint FK44j0v4g89hhdoe09s8fp7kos6
            references dbo.categories
)
go


-- Account: role is stored directly in this table.
IF OBJECT_ID('dbo.account', 'U') IS NULL
CREATE TABLE dbo.account
(
    account_id BIGINT IDENTITY(1,1) PRIMARY KEY,
    [role] VARCHAR(20) NOT NULL
        CONSTRAINT CK_account_role CHECK ([role] IN ('Admin', 'Staff', 'User')),
    email VARCHAR(255) NOT NULL
        CONSTRAINT UQ_account_email UNIQUE,
    [password] VARCHAR(255) NOT NULL
);
GO

-- Insert missing sample rows only; existing data is preserved.
SET XACT_ABORT ON;
BEGIN TRANSACTION;

INSERT INTO dbo.categories (category_name)
SELECT v.category_name
FROM (VALUES
    ('Vegetables'), ('Fruits'), ('Meat'), ('Seafood'), ('Dairy'),
    ('Grains'), ('Spices'), ('Oils'), ('Nuts'), ('Beverages')
) AS v(category_name)
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.categories c WHERE c.category_name = v.category_name
);

INSERT INTO dbo.ingredients
    (entry_date, ingredient_name, price_from, price_to, producer_name, supplier, category_id)
SELECT v.entry_date, v.ingredient_name, v.price_from, v.price_to,
       v.producer_name, v.supplier, c.category_id
FROM (VALUES
    (CAST('2026-10-01' AS DATE), 'Carrot',       15000,  25000, 'Da Lat Farm',    'Fresh Market',  'Vegetables'),
    (CAST('2026-10-01' AS DATE), 'Apple',        40000,  65000, 'Green Orchard',  'Fruit World',   'Fruits'),
    (CAST('2026-10-01' AS DATE), 'Chicken',      70000, 100000, 'Viet Poultry',   'Food Supply',   'Meat'),
    (CAST('2026-10-01' AS DATE), 'Shrimp',      120000, 180000, 'Nha Trang Sea',  'Ocean Foods',   'Seafood'),
    (CAST('2026-10-01' AS DATE), 'Fresh Milk',   25000,  35000, 'Dairy Farm',     'Milk Shop',     'Dairy'),
    (CAST('2026-10-01' AS DATE), 'Rice',         18000,  30000, 'Mekong Rice',    'Rice Supply',   'Grains'),
    (CAST('2026-10-01' AS DATE), 'Black Pepper', 80000, 120000, 'Highland Spice', 'Spice Store',   'Spices'),
    (CAST('2026-10-01' AS DATE), 'Cooking Oil',  35000,  55000, 'Golden Oil',     'Grocery Store', 'Oils'),
    (CAST('2026-10-01' AS DATE), 'Cashew',      150000, 220000, 'Binh Phuoc Nut', 'Nut House',     'Nuts'),
    (CAST('2026-10-01' AS DATE), 'Green Tea',    50000,  90000, 'Thai Nguyen Tea','Tea Shop',      'Beverages')
) AS v(entry_date, ingredient_name, price_from, price_to, producer_name, supplier, category_name)
JOIN dbo.categories c ON c.category_name = v.category_name
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.ingredients i WHERE i.ingredient_name = v.ingredient_name
);

-- Demo passwords for classroom use only.
-- In a real application, store password hashes generated by its password hasher.
INSERT INTO dbo.account ([role], email, [password])
SELECT v.[role], v.email, v.[password]
FROM (VALUES
    ('Admin', 'admin@example.com',  'Admin@123'),
    ('Staff', 'staff1@example.com', 'Staff@123'),
    ('Staff', 'staff2@example.com', 'Staff@123'),
    ('User',  'user1@example.com',  'User@123'),
    ('User',  'user2@example.com',  'User@123'),
    ('User',  'user3@example.com',  'User@123'),
    ('User',  'user4@example.com',  'User@123'),
    ('User',  'user5@example.com',  'User@123'),
    ('User',  'user6@example.com',  'User@123'),
    ('User',  'user7@example.com',  'User@123')
) AS v([role], email, [password])
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.account a WHERE a.email = v.email
);

COMMIT TRANSACTION;
GO

SELECT * FROM dbo.categories;
SELECT * FROM dbo.ingredients;
SELECT account_id, [role], email FROM dbo.account;
GO
